workflows:
  parnassas_android_build:
    name: Parnassas Android Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17
      android_signing:
        - parnassa_upload_keystore

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Validate project
        script: |
          flutter analyze
          flutter test

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - dev.aaq.92@gmail.com
        notify:
          success: true
          failure: true
